# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/comandos',
                'doc_host': 'https://galicae.github.io',
                'git_url': 'https://github.com/galicae/comandos',
                'lib_path': 'comandos'},
  'syms': { 'comandos.core': {'comandos.core.procrustes': ('util.html#procrustes', 'comandos/core.py')},
            'comandos.plot': { 'comandos.plot._plot_clustermap': ('plot.html#_plot_clustermap', 'comandos/plot.py'),
                               'comandos.plot._plotly_clustermap': ('plot.html#_plotly_clustermap', 'comandos/plot.py'),
                               'comandos.plot.highlighted_dimplot': ('plot.html#highlighted_dimplot', 'comandos/plot.py'),
                               'comandos.plot.plot_overview': ('plot.html#plot_overview', 'comandos/plot.py')},
            'comandos.report': {'comandos.report.plot_overview': ('report.html#plot_overview', 'comandos/report.py')},
            'comandos.util': { 'comandos.util.find_center': ('util.html#find_center', 'comandos/util.py'),
                               'comandos.util.grouped_obs_mean': ('util.html#grouped_obs_mean', 'comandos/util.py'),
                               'comandos.util.grouped_obs_percent': ('util.html#grouped_obs_percent', 'comandos/util.py'),
                               'comandos.util.grouped_obs_present': ('util.html#grouped_obs_present', 'comandos/util.py'),
                               'comandos.util.map_fine_to_coarse': ('util.html#map_fine_to_coarse', 'comandos/util.py'),
                               'comandos.util.procrustes': ('util.html#procrustes', 'comandos/util.py')}}}
