# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/comandos',
                'doc_host': 'https://galicae.github.io',
                'git_url': 'https://github.com/galicae/comandos',
                'lib_path': 'comandos'},
  'syms': { 'comandos.core': {'comandos.core.procrustes': ('util.html#procrustes', 'comandos/core.py')},
            'comandos.util': { 'comandos.util.grouped_obs_mean': ('util.html#grouped_obs_mean', 'comandos/util.py'),
                               'comandos.util.grouped_obs_percent': ('util.html#grouped_obs_percent', 'comandos/util.py'),
                               'comandos.util.grouped_obs_present': ('util.html#grouped_obs_present', 'comandos/util.py'),
                               'comandos.util.procrustes': ('util.html#procrustes', 'comandos/util.py')}}}
